---
number-sections: false
author: Chair of Computational Molecular Medicine Technical University of Munich

subtitle: "Lecture notes of the module Data Analysis and Visualization (IN2339)"
description:
  This book introduces concepts and skills that can help you tackle
  real-world data analysis challenges. It covers concepts from probability, statistical
  inference, regression, and supervised learning and helps you develop skills such
  as Python programming, data wrangling, and data visualization.
bibliography:
  - book.bib
  - packages.bib


execute: 
  kernel: dataviz

date: today


---

# Overview {.unnumbered}

These are the lecture notes of the module the module Data Analysis and Visualization (IN2339).

It is an adaptation to the programming language **Python** of the original script <em><u>[Data Analysis and Visualization in R](https://gagneurlab.github.io/dataviz/)</u></em>.</p>

The theoretical concepts are identical, only the programming language is changed.</p>

This work is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0)

# Acknowledgments {-}

This script has been first put together in the winter semester 2020/2021 by Felix Brechtmann, Alexander Karollus, Daniela Klaproth-Andrade, Pedro Silva, and Julien Gagneur with help from Xueqi Cao, Laura Martens, Ines Scheller, Vangelis Theodorakis, and Vicente Yépez.

We leveraged work from colleagues who helped creating lecture slides since 2017: Žiga Avsec, Ines Assum, Daniel Bader, Jun Cheng, Bašak Eraslan, Mathias Heinig, Jan Krumsieck, Christian Mertes, and Georg Stricker.

The script has been adapted from R to Python in the winter semester 2025/2026 by Xavi Hernandez Alias, Eva Holtkamp, Shubhankar Londhe, Johann Promeuschel, Maria Ryabtseva and Anna Starovoit.


# Prerequisites {-}
Basics in probabilities are required. The Chapters "Summary Statistics", and "Probability" of the Book "Introduction to Data Science Part II" <https://rafalab.dfci.harvard.edu/dsbook-part-2/> make a good refresher. Make sure all concepts are familiar to you. Check your knowledge by trying the exercises. 

# Datasets {#sec-datasets} 
Datasets used in this script are available to download as a compressed file [here](http://shorturl.at/otwxO).

# Feedback {-}
For improvement suggestions, reporting errors and typos, please use the online document [here](https://docs.google.com/document/d/1tdWmtkDaNUnQLkG_cNfJ2KLHwnaldtQwZh6pUQh8Mpc/edit?usp=sharing).

<!-- Latex commands -->
\newcommand{\bs}{\boldsymbol} 
\newcommand{\m}{\mathbf}

\newcommand{\w}{\m w} 
\newcommand{\x}{\m x}
\newcommand{\y}{\m y}

\newcommand{\X}{\m X} 
\newcommand{\I}{\m I} 

\newcommand{\E}{\operatorname{E}} 
\newcommand{\Var}{\operatorname{Var}} 
\newcommand{\Cov}{\operatorname{Cov}} 
